[tool.poetry]
name = "fine-tuning"
version = "0.1.0"
description = ""
authors = ["marykorol98 <mashak.1998@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
